### ISSUE TITLE
auth.login('netrc') not working

### ISSUE THREAD

**Issue by andypbarrett** [nsidc/earthdata#58]
I'm running python 3.7.8 on Ubuntu 16.04 LTS.  

`auth.login(strategy='netrc')`

returns `False`.

Some testing reveals that `os.path.exists("~/.netrc")` returns `False`.

The solution is to use `os.path.exists(os.path.expanduser("~/.netrc"))`

Alternatively, using `netrc` would do all of this.

**Comment by andypbarrett** [comment]
Added a fix to this sorting out access to create PR

**Comment by betolink** [comment]
#59 fixes this so closing!
